
import strutils

iterator permutations[T](s: openarray[T]): seq[T] =
  let n = len(s)
  var pos = newSeq[int](n)
  var current = newSeq[T](n)
  for i in 0..n-1:
    pos[i] = i
  while true:
    for i in 0..n-1:
      current[i] = current[pos[i]]
      current[pos[i]] = s[i]
    yield current
    var i = 1
    while i < n:
      pos[i] -= 1
      if pos[i] < 0:
        pos[i] = i
        i += 1
      else:
        break
    if i >= n:
      break
  
proc operation(a, b: float, symbol: int): float =
  case symbol
  of 1:
    return a - b
  of 2:
    return a * b
  of 3:
    return a / b
  else:
    return a + b

proc operator(symbol: int): string =
  case symbol
  of 1:
    return " - "
  of 2:
    return " * "
  of 3:
    return " / "
  else:
    return " + "

proc stringsToFloats(input: string): seq =
  var 
    strings = input.split()
    floats = newSeq[float](len(strings))
  for i in 0..strings.high:
    floats[i] = parseFloat(strings[i])
  result = floats

while true:
  var
    input = stringsToFloats(readline(stdin))
    answer = input[6]
    numbers = input[0..5]
  for p in permutations(numbers):
    for i in 1..4:
      for j in 1..4:
        for g in 1..4:
          for h in 1..4:
            for k in 1..4:
              var result = operation(operation(operation(operation(operation(p[0], p[1], k), p[2], h), p[3], g), p[4], j), p[5], i)
              if result == answer:
                echo p[0], operator(k), p[1],operator(h), p[2], operator(g), p[3], operator(j), p[4], operator(i), p[5], " = ", result
                

#[

Disclaimer / license for using permutations proc from Reimer Behrends:

Copyright (c) 2014 Reimer Behrends

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

 ]#
